#!/bin/sh
# Writes the Homebrew formula from the archives that `make release` produced.
# Called by `make brew-formula`; reads dist/, writes the formula on stdout.
set -e

: "${VERSION:?set VERSION}"
NAME=jalon
REPO=AltSoyuz/jalon

sha_of() {
	f="dist/$NAME-$1-$VERSION.tar.gz_checksums.txt"
	test -f "$f" || { echo "missing $f, run make release first" >&2; exit 1; }
	# The checksum file is "<sha256>  <filename>", as sha256sum writes it.
	awk '{print $1}' "$f"
}

url_of() {
	echo "https://github.com/$REPO/releases/download/$VERSION/$NAME-$1-$VERSION.tar.gz"
}

cat <<EOF
# Generated by \`make brew-formula\`. Do not edit by hand.
class Jalon < Formula
  desc "File first task manager for humans and agents"
  homepage "https://github.com/$REPO"
  version "${VERSION#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "$(url_of darwin-arm64)"
      sha256 "$(sha_of darwin-arm64)"
    end
    on_intel do
      url "$(url_of darwin-amd64)"
      sha256 "$(sha_of darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$(url_of linux-arm64)"
      sha256 "$(sha_of linux-arm64)"
    end
    on_intel do
      url "$(url_of linux-amd64)"
      sha256 "$(sha_of linux-amd64)"
    end
  end

  def install
    bin.install "$NAME"
  end

  test do
    assert_match "${VERSION#v}", shell_output("#{bin}/$NAME version")
  end
end
EOF
